FROM rust:1.69
#nice

# create Rust-based backend server working directory
WORKDIR /rust-server

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y cmake libjsoncpp-dev

RUN cargo install cargo-watch

# Make needs Go
COPY --from=golang:1.20 /usr/local/go/ /usr/local/go/
ENV PATH="/rust-server/target/debug:/usr/local/go/bin:${PATH}"

# Use terminal colors when running cargo commands
ENV CARGO_TERM_COLOR=always

# Use the sparse cargo protocol, which should cut down on build times
ENV CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse

EXPOSE 8080 
EXPOSE 5300/udp

CMD make all test-plugins && cargo watch --poll -w server -x check -x test -x run --why || tail -f /dev/null
