version: '3.8'

x-modns-sdk:
  &modns-sdk-share
  type: bind
  source: ./modns-sdk

x-makefile:
  &makefile
  type: bind
  source: ./Makefile

services:
  frontend:
    container_name: react-app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    build: 
      context: frontend/dns_frontend
      dockerfile: Dockerfile.Frontend.Dev
    volumes:
      - ./frontend/dns_frontend/src:/react-app/src
      - ./frontend/dns_frontend/public:/react-app/public
      - ./frontend/dns_frontend/package.json:/react-app/package.json
      - ./frontend/dns_frontend/package-lock.json:/react-app/package-lock.json
      - frontend_build:/react-app/build

  backend:
    container_name: rust-server
    build:
      context: .
      dockerfile: Dockerfile.Backend.Dev
    environment:
      MODNS_LOG: modns=debug,info
      MODNS_PATH: /rust-server/plugins
      MODNS_LOG_STYLE: always
    ports:
      - "8080:80"
      - "5300:53"
      - "5300:53/udp"
    volumes:
      - ./server:/rust-server/server
      - ./cli:/rust-server/cli
      # - ./modns-sdk:/rust-server/modns-sdk
      - ./Cargo.toml:/rust-server/Cargo.toml
      # - ./Makefile:/rust-server/Makefile
      - frontend_build:/usr/share/modns/web:ro
      - backend_build:/rust-server/target
      - backend_cache:/root/.cargo/registry
      - plugins_build:/usr/share/modns/default-plugins
      - <<: *makefile
        target: /rust-server/Makefile
      - <<: *modns-sdk-share
        target: /rust-server/modns-sdk
  
  plugins-env:
    container_name: plugins-env
    build:
      context: .
      dockerfile: Dockerfile.Plugins
    volumes:
      - backend_build:/plugins-env/target
      - backend_cache:/root/.cargo/registry
      - ./plugins:/plugins-env/plugins
      - plugins_build:/usr/share/modns/default-plugins
      - <<: *makefile
        target: /plugins-env/Makefile
      - <<: *modns-sdk-share
        target: /plugins-env/modns-sdk

    # make-env:
    #   container_name: make-env
    #   build:
    #     contxt: .
    #     dockerfile: Dockerfile.Makefile
    #   volumes:
    #     - ./Makefile:/make-env


volumes:
  frontend_build:
  backend_build:
  backend_cache:
  plugins_build: