version: '3.8'

services:
  dns_frontend:
    container_name: react-app
    image: frontend-react:latest
    build: 
      context: frontend/dns_frontend
      dockerfile: Dockerfile-dev
    ports: 
      - 3000:3000
    volumes:
      - ./frontend/dns_frontend:/react-app
    command: npm install && npm run build --production