version: '3.8'

services:
  dns_frontend:
    container_name: react-app
    read_only: true
    build: 
      context: frontend/dns_frontend
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - ./frontend/dns_frontend/src:/react-app/src
      - ./frontend/dns_frontend/public:/react-app/public
      - ./frontend/dns_frontend/package.json:/react-app/package.json
      - ./frontend/dns_frontend/package-lock.json:/react-app/package-lock.json
