---

# Files to read from, will be combined into a single document
input-files:
- 1_intro.md
- 2_designProcess.md
- 3_hardware_software.md
- 4_designConsiderations.md
- 5_works_cited.md
- appendices.md

output-file: design_report.pdf
standalone: true

# Only allow pandoc access to this folder and its children
sandbox: true

# Table of Contents settings
table-of-contents: true
toc-depth: 3
number-sections: true

# Metadata passed to latex template
metadata:
  title: "MoDNS: A Modular DNS Solution"
  subtitle: Final Technical Report
  author:
  - Tim Huhn
  - Bronson Jordan
  - Aankit Pokhrel
  - Carter Ray
  - Seth Warren

  abstract: |
    Domain Name System (DNS) is the system in place that translates domain names into IP addresses. This allows user to access websites without the need to memorize seemingly random strings of numbers. DNS Servers respond to requests made by devices in a network with the correct IP address for the requested domain name.
    In addition to the translation functionality, additional amazing services can be done through DNS. Services like PiHole can block requests made for advertisements while the user roams the internet. Another service like LANCache can cache downloads to allow for faster installations of shared sotfware.
    With these services and many other open source additions, user's may want to add multiple services to their local DNS server. However, combining many of these benefits often requires chaining multiple DNS servers to each other until one finally reaches an external DNS server.
    This is a complicated and messy process to combine only a few of the features previously mentioned. MoDNS offers a solution to the typical DNS approach. It allows user to write and load plugins that have the functionality to change how DNS requests on a local network are handled. This provides opporunities to combine many DNS benefits into one MoDNS Server.

  documentclass: report
  papersize: letter
  geometry:
  - margin=0.5in

  fontfamily: bera
  mainfont: Bera Sans

...
