[package]
name = "modnsd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.2.1"
actix-web-lab = { version = "0.18.8", default-features = false }
env_logger = "0.10.0"
tokio = { version = "1.23.0", features = ["full"] }

[dev-dependencies]
cfg-if = "1.0.0"
