name: Rust & Make CI

on:
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!docs/**'
      - '!frontend/**'
      - '!**Dockerfile**'
      - '!**docker**'


env:
  CARGO_TERM_COLOR: always

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Makefile
      run: make plugins test-plugins
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose