name: Build Backend

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
      rust_toolchain:
        required: true
        type: string
      gcc:
        required: false
        type: string


env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        key: ci-build-${{ inputs.architecture }}
        path: target/${{ inputs.rust_toolchain }}

    - name: Install coresponding Rust toolchain
      if: inputs.rust_toolchain != ''
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ inputs.rust_toolchain }}

    - name: Install gcc cross-compiler
      run: sudo apt-get install ${{ inputs.gcc }}

    - name: Build server
      run: make server ARCH=${{ inputs.architecture }}

    - name: Build CLI
      run: make cli ARCH=${{ inputs.architecture }}

    - name: Build plugins
      run: make plugins test-plugins ARCH=${{ inputs.architecture }}
