name: Build and publish Debian package of MoDNS

on:
  push:
    branches:
      - 'release'
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        architecture: [x86_64, aarch64, arm]
        include:
          - architecture: aarch64
            gcc: gcc-aarch64-linux-gnu
            rust_toolchain: aarch64-unknown-linux-gnu
          - architecture: arm
            gcc: gcc-arm-linux-gnueabi
            rust_toolchain: arm-unknown-linux-gnueabi

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create MoDNS package
        run: |
          make install MODNS_INSTALL_PKGDIR=.debpkg
          cd frontend/dns_frontend
          npm run build
          cd ../..
          cp frontend/dns_frontend/build .debpkg/usr/share/web
          mkdir -p .debpkg/usr/lib/modns          
      
      - uses: jiro4989/build-deb-action@v2
        with:
          package: modns
          package_root: .debpkg
          maintainer: MoDNS
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'libc6'
          desc: 'Modular DNS Server (MoDNS).'