name: Backend CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!docs/**'
      - '!frontend/**'
      - '!**Dockerfile**'
      - '!**docker**'

jobs:
  build:
    strategy:
      matrix:
        architecture: [x86_64, aarch64, arm]
        include:
          - architecture: x86_64
            debian_arch: amd64
            rust_toolchain: x86_64-unknown-linux-gnu
          - architecture: aarch64
            debian_arch: arm64
            gcc: gcc-aarch64-linux-gnu
            rust_toolchain: aarch64-unknown-linux-gnu
          - architecture: arm
            debian_arch: arm
            gcc: gcc-arm-linux-gnueabi
            rust_toolchain: arm-unknown-linux-gnueabi

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build backend
        uses: MoDNS/MoDNS/.github/workflow/backend-workdflow.yml
        with:
          architecture: ${{ matrix.architecture }}
          rust_toolchain: ${{ matrix.rust_toolchain }}
          gcc: ${{ matrix.gcc }}

    - name: Run tests
      if: inputs.architecture == 'x86_64'
      run: make test ARCH=${{ matrix.architecture }}