name: CI Workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!docs/**'
      - '!frontend/**'
      - '!**Dockerfile**'
      - '!**docker**'

jobs:
  build:
    uses: MoDNS/MoDNS/.github/workflows/backend-workflow.yml@main
    strategy:
      matrix:
        architecture: [x86_64, aarch64, arm]
        include:
          - architecture: x86_64
            rust_toolchain: x86_64-unknown-linux-gnu
            gcc: gcc-x86-64-linux-gnu
          - architecture: aarch64
            gcc: gcc-aarch64-linux-gnu
            rust_toolchain: aarch64-unknown-linux-gnu
          - architecture: arm
            gcc: gcc-arm-linux-gnueabi
            rust_toolchain: arm-unknown-linux-gnueabi
    with:
      architecture: ${{ matrix.architecture }}
      rust_toolchain: ${{ matrix.rust_toolchain }}
      gcc: ${{ matrix.gcc }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: make test ARCH=${{ matrix.architecture }}
