name: Package for Debian

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  package:
    strategy:
      matrix:
        architecture: [x86_64, aarch64, arm]
        include:
          - architecture: x86_64
            debian_arch: amd64
            rust_toolchain: x86_64-unknown-linux-gnu
          - architecture: aarch64
            debian_arch: arm64
            gcc: gcc-aarch64-linux-gnu
            rust_toolchain: aarch64-unknown-linux-gnu
          - architecture: arm
            debian_arch: arm
            gcc: gcc-arm-linux-gnueabi
            rust_toolchain: arm-unknown-linux-gnueabi

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build backend
        uses: MoDNS/MoDNS/.github/workflow/backend-workdflow.yml
        with:
          architecture: ${{ matrix.architecture }}
          rust_toolchain: ${{ matrix.rust_toolchain }}
          gcc: ${{ matrix.gcc }}

      - name: Build frontend
        uses: MoDNS/MoDNS/.github/workflow/react-workflow.yml

      - name: Copy Files Into Package
        run: |
          make install MODNS_INSTALL_PKGDIR=.debpkg ARCH=${{ matrix.architecture }}
          cp frontend/dns_frontend/build/* .debpkg/usr/share/web
          mkdir -p .debpkg/usr/lib/modns
      
      - name: Create Debian Package
        uses: jiro4989/build-deb-action@v2
        with:
          package: modns
          package_root: .debpkg
          maintainer: MoDNS
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: ${{ matrix.debian_arch }}
          depends: 'libc6'
          desc: 'Modular DNS Server (MoDNS).'

      - name: Upload package file
        uses: actions/upload-artifact@v3\
        with:
          name: modns-deb-${{ matrix.architecture }}
          path: ${{ steps.create_debian_package.outputs.file_name }}