name: Node.js CI

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/dns_frontend/**'
      - '!**Dockerfile**'
      - '!**docker**'

defaults:
  run:
    working-directory: frontend/dns_frontend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - run: npm run build --if-present
      - uses: actions/upload-artifacts@v3
        with:
          name: frontend-build-${{ github.ref }}
          path: frontend/dns_frontend/build
